const {chromium}=require('playwright');const {spawnSync}=require('child_process');const path=require('path');
(async()=>{const browser=await chromium.launch({headless:true,channel:process.env.LAB_BROWSER_CHANNEL||undefined});try{
const page=await browser.newPage({viewport:{width:1400,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(process.env.LAB_URL);await page.locator('#key').fill(process.env.LAB_KEY);await page.getByRole('button',{name:'连接',exact:true}).click();await page.locator('#workspace').waitFor({state:'visible'});
async function actor(id){await page.locator('#actor').selectOption(id);}
async function form(title,fields){await page.getByText(title,{exact:true}).click();const container=page.locator('#learning-list > details').filter({has:page.getByText(title,{exact:true})});for(const [label,value]of Object.entries(fields)){const e=container.getByLabel(label,{exact:true});if(await e.evaluate(e=>e.tagName)==='SELECT')await e.selectOption(value);else await e.fill(value);}await container.getByRole('button',{name:'记录：'+title,exact:true}).click();await page.waitForFunction(()=>!busy);if(await page.locator('#notice').getAttribute('class')==='error')throw Error(await page.locator('#notice').innerText());}
await actor('H1');await form('1 · 提出候选认知',{'来源 Return':'R1','独立验证 Human':'H3','修订自哪个知识版本':'none','核心主张':'Synthetic fixture supports a traceable bounded reuse route','适用情境':'Local synthetic tasks only','所需操作边界（逗号分隔）':'read','候选机制解释':'Protocol trace may help reproduce the fixture','迁移条件与不适用情形':'Same local fixture; no real business extrapolation','本轮适用 Task 编号（逗号分隔）':'T2'});
const kid=await page.evaluate(()=>Object.keys(state.LearningClaim)[0]);
for(const i of [1,2]){await actor('H'+i);await form('2 · 关联证据',{'对应候选主张':kid,'证据来源 Return':'R'+i,'与主张的关系':'supports','证据关系及理由':'Independent synthetic fixture source; not empirical research','共同上游来源标识（逗号分隔，必须如实填写）':'synthetic-source-'+i});}
const ids=await page.evaluate(()=>Object.keys(state.LearningEvidence).join(','));await actor('H3');await form('3 · 反证与独立验证',{'待验证主张':kid,'判断':'validated','所有相关 Evidence 编号（逗号分隔）':ids,'反证尝试及观察结果':'Synthetic negative-path tests, no real causal proof','替代解释':'Fixture bias and shared implementation','局限与未验证范围':'Only protocol correctness','证据独立性判断依据':'Separate declared synthetic sources, not real independent experimental evidence'});
await actor('H1');await form('4 · 整理候选能力包',{'已捕获候选路线':'route/R1','依赖的知识版本':kid,'数据及版本':'Synthetic fixture v1','工具及版本':'Local protocol Client','Agent 配置':'Explicit read scope only','运行环境':'Local test process','可复现方法':'Use bounded claim as context, then produce formal Return','Human 审查与监督需求':'H2 Review, H1 Acceptance; no production authority'});
const code=`import json,os
from pathlib import Path
from organization.agent_client import Client
i=json.loads(Path(os.environ['LAB_IDENTITY']).read_text());c=Client(os.environ['LAB_URL'],i['token'])
k=c.request('/v1/knowledge')['knowledge'];assert len(k)==1 and 'evidence_ids' not in k[0];kid=k[0]['id']
c.command('claim',{'id':'E3','task_id':'T2','hau_id':'U3'},'learn/claim')
c.command('ack',{'execution_id':'E3'},'learn/ack')
c.command('use_knowledge',{'id':'USE3','execution_id':'E3','knowledge_id':kid,'decision':'adopted','reason':'Matches explicit fixture context','package_id':'route/R1'},'learn/use')
c.command('submit',{'id':'R3','execution_id':'E3','result':'Synthetic bounded reuse of '+kid,'observed_terrain':'Same local fixture','major_execution_facts':'Fetched authorized knowledge, recorded adoption, returned result','reflection':'No model or causal efficacy claim'},'learn/return')`;
const child=spawnSync(process.env.LAB_PYTHON,['-c',code],{encoding:'utf8'});if(child.status!==0)throw Error('Agent reuse process failed: '+child.stderr);
await page.getByRole('button',{name:'刷新状态'}).click();await page.waitForFunction(()=>!!state.Return?.R3);await actor('H2');const result=page.locator('#return-list article').filter({has:page.getByRole('heading',{name:'T2 / R3 · 成功',exact:true})});await result.getByLabel('1 · Review：结果可信度').selectOption('true');await result.getByLabel('审查证据（必填）').fill('Synthetic trace inspected');await result.getByRole('button',{name:'记录 Review',exact:true}).click();await page.waitForFunction(()=>!busy);await actor('H1');await result.getByLabel('2 · Acceptance：是否符合任务标准').selectOption('true');await result.getByLabel('验收理由（必填）').fill('Synthetic criterion only');await result.getByRole('button',{name:'记录 Acceptance'}).click();await page.waitForFunction(()=>!busy);
await actor('H3');await form('6 · 关联后续结果',{'使用记录':'USE3','同一 Execution 的 Return':'R3','结果观察与解释（不默认归因于知识）':'Successful fixture outcome; association is not causation'});
await actor('H1');await form('7 · 核对另一 HAU 的复现',{'能力包':'route/R1','采用记录':'USE3','复现 Return':'R3'});
await page.locator('#learning').scrollIntoViewIfNeeded();await page.locator('#learning').screenshot({path:path.join(process.env.LAB_OUTPUT,'learning-focus.png')});await page.screenshot({path:path.join(process.env.LAB_OUTPUT,'learning-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile overflow');await page.screenshot({path:path.join(process.env.LAB_OUTPUT,'learning-mobile.png'),fullPage:true});if(errors.length)throw Error(errors.join(';'));
}finally{await browser.close();}})().catch(e=>{console.error(e.message);process.exit(1)});
