const {chromium}=require('playwright'),path=require('path');
(async()=>{const browser=await chromium.launch({headless:true,channel:process.env.LAB_BROWSER_CHANNEL||'msedge'});try{
const a=await browser.newPage({viewport:{width:1280,height:960}}),b=await browser.newPage();const errors=[];for(const p of [a,b])p.on('pageerror',e=>errors.push(e.message));
async function register(p,username){await p.goto(process.env.LAB_URL);await p.locator('#username').fill(username);await p.locator('#password').fill('synthetic-browser-password');await p.locator('#display-name').fill(username);await p.getByRole('button',{name:'注册账号',exact:true}).click();await p.locator('#workspace').waitFor({state:'visible'});}
async function settled(p){await p.waitForFunction(()=>!busy);if(await p.locator('#notice').getAttribute('class')==='error')throw Error(await p.locator('#notice').innerText());}
await register(a,'alice');await register(b,'bob');await a.reload();await a.locator('#workspace').waitFor({state:'visible'});if(!await a.locator('#actor').isDisabled())throw Error('Human switch not disabled');
await a.getByLabel('希望实现什么变化',{exact:true}).fill('合成网页接入验证');await a.getByLabel('目标成功标准',{exact:true}).fill('完整的注册授权与 Return 记录');await a.getByRole('button',{name:'创建目标',exact:true}).click();await settled(a);
await a.getByLabel('任务预期结果',{exact:true}).fill('验证网页协议客户端');await a.getByLabel('任务验收标准',{exact:true}).fill('明确标识测试结果，保留授权和提交记录');const bob=await a.evaluate(()=>Object.values(state.Human).find(h=>h.display_name==='bob').id);await a.getByLabel('谁审查结果可信度',{exact:true}).selectOption(bob);await a.getByRole('button',{name:'保存任务',exact:true}).click();await settled(a);await a.getByRole('button',{name:'发布任务：验证网页协议客户端',exact:true}).click();await settled(a);
await a.locator('nav a[href="#agents"]').click();await a.locator('#agent-name').fill('网页协议客户端');await a.getByRole('button',{name:'创建接入凭据',exact:true}).click();await a.waitForFunction(()=>document.getElementById('connection').textContent.includes('token'));const connection=JSON.parse(await a.locator('#connection').innerText());await a.getByLabel('任务：验证网页协议客户端',{exact:true}).check();for(const p of ['claim','ack','submit'])await a.getByLabel(p,{exact:true}).check();await a.getByRole('button',{name:'批准注册',exact:true}).click();await settled(a);
await a.getByText('没有外部 Agent？使用浏览器协议测试客户端',{exact:true}).click();await a.locator('#agent-token').fill(connection.token);await a.getByRole('button',{name:'连接 Agent 并读取任务',exact:true}).click();await a.locator('#agent-task option').waitFor({state:'attached'});await a.getByRole('button',{name:'运行协议测试',exact:true}).click();await a.waitForFunction(()=>Object.keys(state.Return||{}).length===1);await settled(a);
const count=await a.evaluate(()=>events.length);await a.getByRole('button',{name:'运行协议测试',exact:true}).click();await settled(a);if(await a.evaluate(()=>events.length)!==count)throw Error('Duplicate browser run changed events');
await b.evaluate(()=>refresh());await b.locator('nav a[href="#results"]').click();await b.getByLabel('1 · Review：结果可信度').selectOption('true');await b.getByLabel('审查证据（必填）').fill('合成测试，仅检查协议记录');await b.getByRole('button',{name:'记录 Review',exact:true}).click();await settled(b);
await a.evaluate(()=>refresh());await a.locator('nav a[href="#results"]').click();await a.getByLabel('2 · Acceptance：是否符合任务标准').selectOption('true');await a.getByLabel('验收理由（必填）').fill('满足声明的协议测试标准');await a.getByRole('button',{name:'记录 Acceptance',exact:true}).click();await settled(a);await a.getByLabel('3 · Selection：选择此结果的理由').fill('保留这条合成协议验证记录');await a.getByRole('button',{name:'选择采用此结果',exact:true}).click();await settled(a);
await a.evaluate(()=>document.getElementById('agent-token').value='');await a.evaluate(()=>document.getElementById('connection').textContent='接入凭据已从截图中清除');await a.locator('nav a[href="#agents"]').click();await a.screenshot({path:path.join(process.env.LAB_OUTPUT,'portal-desktop.png'),fullPage:true});await a.setViewportSize({width:390,height:844});if(await a.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile overflow');await a.screenshot({path:path.join(process.env.LAB_OUTPUT,'portal-mobile.png'),fullPage:true});await a.getByRole('button',{name:'退出',exact:true}).click();await a.locator('#login').waitFor({state:'visible'});if(errors.length)throw Error(errors.join(';'));
console.log('PASS: two browser accounts -> goal/task -> scoped Agent -> Return -> separate review/acceptance/selection, reload and logout');
}finally{await browser.close();}})().catch(e=>{console.error(e.message);process.exit(1)});
