"use strict";
let token='', state={}, events=[], busy=false;
const pendingKeys=new Map();
const $=id=>document.getElementById(id), values=k=>Object.values(state[k]||{});
const labels={pending:'等待授权',approved:'已授权',revoked:'已撤销',published:'已发布',closed:'已关闭',running:'执行中',blocked:'已阻塞',interrupted:'已中断',submitted:'已提交',claimed:'已领取',success:'成功',failure:'失败',released:'已释放'};
function node(tag,text,parent){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(parent)parent.append(e);return e;}
function message(text,error=false){$('notice').textContent=text;$('notice').className=error?'error':'';}
async function api(path,body){const response=await fetch(path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw new Error(data.error||'请求失败');return data;}
function field(parent,title,value='',tag='input'){const l=node('label',title,parent),e=node(tag,undefined,l);e.value=value;e.setAttribute('aria-label',title);return e;}
function select(parent,title,options){const e=field(parent,title,'','select');for(const [value,text]of options){const o=node('option',text,e);o.value=value;}return e;}
function button(parent,title,action,disabled=false){const b=node('button',title,parent);b.disabled=disabled;b.onclick=async()=>{if(busy)return;busy=true;b.disabled=true;try{await action();}catch(e){message(e.message,true);}finally{busy=false;b.disabled=disabled;}};return b;}
function dump(parent,title,value){const d=node('details',undefined,parent);node('summary',title,d);node('pre',typeof value==='string'?value:JSON.stringify(value,null,2),d);}
async function command(name,data){const signature=JSON.stringify([$ ('actor').value,name,data]);if(!pendingKeys.has(signature))pendingKeys.set(signature,'human-web/'+crypto.randomUUID());await api('/control/commands',{actor:$('actor').value,command:name,data,idempotency_key:pendingKeys.get(signature)});pendingKeys.delete(signature);message('已记录：'+name);await refresh();}
async function refresh(){const a=$('actor').value;const data=await api('/control/state');const log=await api('/control/events');state=data.state;events=log.events;$('actor').replaceChildren();for(const h of values('Human')){const o=node('option',h.display_name+' · '+h.id,$('actor'));o.value=h.id;}if(values('Human').some(h=>h.id===a))$('actor').value=a;render();}
function card(parent,title){const c=node('article',undefined,parent);c.className='card';node('h3',title,c);return c;}
function render(){for(const id of ['counts','agent-list','task-list','boundary-list','return-list','event-list'])$(id).replaceChildren();
for(const [name,count]of [['待审批 Agent',values('AgentRegistration').filter(r=>r.status==='pending').length],['执行记录',values('Execution').length],['正式 Return',values('Return').length]])card($('counts'),name+' · '+count);
if(!values('Human').length)node('p','尚无测试身份和任务。请先按启动文档运行 init-fixture。',$('agent-list'));
for(const r of values('AgentRegistration')){const c=card($('agent-list'),r.name+' · '+(labels[r.status]||r.status));node('p','注册编号：'+r.id,c);dump(c,'声明能力与当前授权',r);
if(r.status==='pending'){const hau=field(c,'HAU 编号（绑定当前 Human）','U0');const tasks=field(c,'允许的 Task 编号（逗号分隔）','');node('p','仅选择这次任务必要的操作。能力声明不会自动获得权限。',c);const permissions=[];for(const name of ['claim','ack','progress','submit','fail','release','blocked','escalate','request_boundary','resume','challenge_goal','use_knowledge']){const label=node('label',undefined,c),check=node('input',undefined,label);check.type='checkbox';check.value=name;label.append(document.createTextNode(name));permissions.push(check);}button(c,'批准注册',()=>command('approve_agent',{registration_id:r.id,hau_id:hau.value.trim(),allowed_tasks:tasks.value.split(',').map(x=>x.trim()).filter(Boolean),permissions:permissions.filter(x=>x.checked).map(x=>x.value)}));}
if(r.status==='approved')button(c,'撤销授权',()=>command('revoke_agent',{registration_id:r.id}),$('actor').value!==r.human_id);}
if(!values('AgentRegistration').length)node('p','暂无注册申请。独立 Agent 注册后，点击刷新查看。',$('agent-list'));
for(const t of values('Task')){const c=card($('task-list'),t.id+' · '+(labels[t.status]||t.status));node('p',t.expected_output,c);node('p','验收标准：'+t.acceptance_criteria,c);node('p','Review '+t.review_authority+' / Acceptance '+t.acceptance_authority+' / Selection '+t.selection_authority,c);for(const e of values('Execution').filter(e=>e.task_id===t.id)){dump(c,'Execution '+e.id+' · '+(labels[e.status]||e.status)+' · Human '+e.accountable_owner,e);if(['blocked','interrupted'].includes(e.status)){const summary=field(c,'恢复说明 · '+e.id,'','textarea');button(c,'恢复执行 '+e.id,()=>{if(!summary.value.trim())throw Error('请填写恢复说明');return command('resume',{execution_id:e.id,summary:summary.value});},$('actor').value!==e.accountable_owner||values('BoundaryRequest').some(r=>r.execution_id===e.id&&r.status==='pending'));}for(const sig of values('WorkSignal').filter(s=>s.execution_id===e.id))node('p',sig.kind+'：'+sig.summary,c);}}
for(const r of values('BoundaryRequest')){const c=card($('boundary-list'),r.id+' · '+r.status);dump(c,'申请内容',r);if(r.status==='pending'){const decision=select(c,'Human 决定',[['rejected','拒绝扩权'],['approved','批准申请范围']]);button(c,'记录边界决定',()=>command('decide_boundary',{request_id:r.id,decision:decision.value}),$('actor').value!==r.authority);}}
for(const r of values('Return')){const e=state.Execution[r.execution_id],t=state.Task[e.task_id],c=card($('return-list'),t.id+' / '+r.id+' · '+(labels[r.outcome]||r.outcome));for(const [k,title]of [['result','结果'],['observed_terrain','观察'],['major_execution_facts','主要执行事实'],['reflection','反思']]){node('strong',title,c);node('pre',r[k],c);}const review=values('Review').find(x=>x.return_id===r.id),accept=values('Acceptance').find(x=>x.return_id===r.id);if(!review){const credible=select(c,'1 · Review：结果可信度',[['false','不可信 / 证据不足'],['true','可信']]),evidence=field(c,'审查证据（必填）','','textarea');button(c,'记录 Review',()=>{if(!evidence.value.trim())throw Error('请填写审查证据');return command('review',{id:crypto.randomUUID(),return_id:r.id,credible:credible.value==='true',evidence:evidence.value});},$('actor').value!==t.review_authority);}else{dump(c,'1 · Review 已记录',review);if(!accept){const accepted=select(c,'2 · Acceptance：是否符合任务标准',[['false','不予验收'],['true','验收通过']]),rationale=field(c,'验收理由（必填）','','textarea');button(c,'记录 Acceptance',()=>{if(!rationale.value.trim())throw Error('请填写验收理由');return command('accept',{id:crypto.randomUUID(),return_id:r.id,review_id:review.id,accepted:accepted.value==='true',rationale:rationale.value});},$('actor').value!==t.acceptance_authority);}else{dump(c,'2 · Acceptance 已记录',accept);if(accept.accepted&&t.status==='published'){const rationale=field(c,'3 · Selection：选择此结果的理由','','textarea');button(c,'选择采用此结果',()=>{if(!rationale.value.trim())throw Error('请填写选择理由');return command('select',{id:crypto.randomUUID(),task_id:t.id,return_id:r.id,rationale:rationale.value});},$('actor').value!==t.selection_authority);}}}for(const selection of values('Selection').filter(x=>x.return_id===r.id))dump(c,'3 · Selection 已记录',selection);}
if(!values('Return').length)node('p','Agent 尚未提交正式结果。',$('return-list'));renderLearning();for(const event of events.slice(-100).reverse())dump($('event-list'),'事件 '+(event.sequence||event.id||'')+' · '+(event.event_type||event.type||''),event);node('p','共 '+events.length+' 条，显示最近 100 条。',$('event-list'));}
$('connect').onclick=async()=>{token=$('key').value.trim();$('key').value='';try{await refresh();$('login').hidden=true;$('workspace').hidden=false;message('已连接本地合成测试环境。');}catch(e){token='';message('连接失败：'+e.message,true);}};
$('refresh').onclick=()=>refresh().catch(e=>message(e.message,true));$('actor').onchange=render;
$('logout').onclick=()=>{token='';state={};events=[];pendingKeys.clear();$('workspace').hidden=true;$('login').hidden=false;for(const id of ['counts','agent-list','task-list','boundary-list','return-list','event-list','actor','learning-list'])$(id).replaceChildren();message('已退出，页面中的控制密钥已清除。');};
