"use strict";
let csrf='',currentHuman='';
async function portalApi(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json','X-CSRF-Token':csrf}:{},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(d.error||'请求失败');return d;}
async function enter(){const me=await portalApi('/api/me');csrf=me.csrf;currentHuman=me.human;await refresh();$('login').hidden=true;$('workspace').hidden=false;showPanel();$('password').value='';message('已登录，选择下一步操作。');}
async function authenticate(create){try{if(create)await portalApi('/api/signup',{username:$('username').value,name:$('display-name').value,password:$('password').value});const r=await portalApi('/api/login',{username:$('username').value,password:$('password').value});csrf=r.csrf;await enter();}catch(e){message(e.message,true);}}
$('signin').onclick=()=>authenticate(false);$('signup').onclick=()=>authenticate(true);
$('refresh').onclick=()=>refresh().catch(e=>message(e.message,true));
$('logout').onclick=async()=>{try{await portalApi('/api/logout',{});location.reload();}catch(e){message(e.message,true);}};
$('create-agent').onclick=async()=>{try{const r=await portalApi('/api/agent',{name:$('agent-name').value});$('connection').textContent=JSON.stringify({url:location.origin,registration_id:r.registration_id,token:r.token,instructions_url:location.origin+'/agent-guide.txt',protocol:'Bearer token; GET /v1/me, /v1/tasks, /v1/executions; POST /v1/commands'},null,2);await refresh();message('凭据已生成，尚未授权。请保存并选择允许的任务和操作。');}catch(e){message(e.message,true);}};
$('copy-connection').onclick=()=>navigator.clipboard.writeText($('connection').textContent).then(()=>message('已复制，请仅交给你的 Agent。')).catch(()=>message('浏览器未允许复制，请手动选择配置文本。',true));
function renderSetup(){const root=$('setup-forms');root.replaceChildren();
 const goal=card(root,'1 · 创建目标');const desire=field(goal,'希望实现什么变化'),criteria=field(goal,'目标成功标准'),boundary=field(goal,'允许的操作（逗号分隔）','read');const gid='G-'+crypto.randomUUID();button(goal,'创建目标',()=>command('activate_goal',{id:gid,desired_change:desire.value,success_criteria:criteria.value,boundary:boundary.value.split(',').map(s=>s.trim()).filter(Boolean),goal_authority:currentHuman}));
 const task=card(root,'2 · 创建任务');const goals=values('Goal').filter(g=>g.goal_authority===currentHuman&&g.status==='active');if(!goals.length){node('p','先创建目标，才能拆分任务。',task);return;}
 const g=select(task,'所属目标',goals.map(g=>[g.id,g.desired_change]));const expected=field(task,'任务预期结果'),acceptance=field(task,'任务验收标准'),bounds=field(task,'任务操作范围（逗号分隔）',goals[0].boundary.join(','));g.onchange=()=>bounds.value=state.Goal[g.value].boundary.join(',');const people=values('Human').map(h=>[h.id,h.display_name]);const reviewer=select(task,'谁审查结果可信度',people),acceptor=select(task,'谁验收任务标准',people),selector=select(task,'谁选择最终结果',people);node('p','三项决定分开记录。可邀请其他人注册后，分别指定责任人。',task);const tid='T-'+crypto.randomUUID();button(task,'保存任务',()=>command('create_task',{id:tid,primary_goal:g.value,expected_output:expected.value,acceptance_criteria:acceptance.value,boundary:bounds.value.split(',').map(s=>s.trim()).filter(Boolean),execution_mode:'parallel',review_authority:reviewer.value,acceptance_authority:acceptor.value,selection_authority:selector.value}));
 for(const t of values('Task').filter(t=>t.status==='draft'&&state.Goal[t.primary_goal].goal_authority===currentHuman))button(root,'发布任务：'+t.expected_output,()=>command('publish',{task_id:t.id}));
}
async function agentApi(path,body){const r=await fetch('/v1/'+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+$('agent-token').value,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(d.error||'Agent 请求失败');return d;}
$('agent-tasks').onclick=async()=>{try{const d=await agentApi('tasks');$('agent-task').replaceChildren();for(const t of d.tasks){const o=node('option',t.expected_output,$('agent-task'));o.value=t.id;}message(d.tasks.length?'请选择任务，再运行协议测试。':'尚无已授权的可执行任务。');}catch(e){message(e.message,true);}};
let testRun=null;
$('agent-run').onclick=async()=>{if(busy)return;busy=true;try{const reg=(await agentApi('me')).registration;const task=$('agent-task').value;if(!task)throw Error('请先连接 Agent 并选择任务');if(!testRun||testRun.task!==task||testRun.registration!==reg.id)testRun={id:'browser-'+crypto.randomUUID(),task,registration:reg.id};const id=testRun.id;const cmd=(command,data,step)=>agentApi('commands',{command,data,idempotency_key:id+'/'+step});await cmd('claim',{id,task_id:task,hau_id:reg.hau_id},'claim');await cmd('ack',{execution_id:id},'ack');await cmd('submit',{id:'R-'+id,execution_id:id,result:'浏览器协议测试完成（非业务成果）',observed_terrain:'明确标识的测试组织任务',major_execution_facts:'经明确授权领取任务、确认执行并提交正式 Return；未调用模型',reflection:'仅证明接入与提交协议可用，不能证明实际业务任务已完成'},'return');await refresh();message('协议测试 Return 已提交，请由指定账号分别审查和验收。');}catch(e){message(e.message,true);}finally{busy=false;}};
enter().catch(()=>{});

function showPanel(){const selected=location.hash.slice(1)||'setup';for(const id of ['setup','agent-connect','agents','tasks','results','learning','events'])$(id).hidden=!(id===selected||(selected==='agents'&&id==='agent-connect'));}
window.addEventListener('hashchange',showPanel);
